import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/components/app-layout";
import font from "@/components/lib/fonts";

export const metadata: Metadata = {
  title: "Skill Ventures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${font.className}`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
